"""Add SourceMaps model and source_map_id to Street

Revision ID: 20251125_120000
Revises: 9044beccc2b2
Create Date: 2025-11-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251125_120000'
down_revision = '9044beccc2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('decade', sa.String(length=20), nullable=False),
    sa.Column('gcs_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('gcs_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('streets_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_map_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_streets_source_map_id', 'source_maps', ['source_map_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_streets_source_map_id', type_='foreignkey')
        batch_op.drop_column('source_map_id')

    op.drop_table('source_maps')
    # ### end Alembic commands ###
