"""initial schema

Revision ID: 9044beccc2b2
Revises:
Create Date: 2025-11-18 12:08:42.016239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9044beccc2b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('decade', sa.String(length=20), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=True),
    sa.Column('main_name', sa.String(length=200), nullable=False),
    sa.Column('main_name_cs', sa.String(length=200), nullable=False),
    sa.Column('variants', sa.Text(), nullable=True),
    sa.Column('misspellings', sa.Text(), nullable=True),
    sa.Column('is_rejected', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streets', schema=None) as batch_op:
        batch_op.create_index('idx_user_city_decade_name', ['user_id', 'city', 'decade', 'main_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streets', schema=None) as batch_op:
        batch_op.drop_index('idx_user_city_decade_name')

    op.drop_table('streets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
